import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://frtxsynlvwhpnzzgfgbt.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydHhzeW5sdndocG56emdmZ2J0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTUzMzk0MCwiZXhwIjoyMDU3MTA5OTQwfQ.rtTe52SEPE8oKXuK0tU4ZzvGB8GCzStQs_4koa8XW2g'
);

const cities = [
  // TIER 1
  {
    name: "Dallas, TX",
    slug: "dallas",
    market_trends: `Dallas-Fort Worth continues to be one of the nation's top-performing commercial real estate markets heading into 2026. The median home price sits around $376,000 as of Q3 2025, with DFW multifamily cap rates averaging 5.7% and Class A office rents in Uptown hitting $41–44/SF NNN. The metro added over 170,000 residents in 2024, maintaining its status as the fastest-growing large metro in the U.S. Corporate relocations continue at a brisk pace, with financial services and technology firms driving office absorption in Plano, Frisco, and Richardson.

Industrial remains the strongest sector, with over 40 million square feet of speculative development delivered in 2024–2025, though vacancy has ticked up to around 8% as the market absorbs new supply. Multifamily rent growth has moderated to 1–2% year-over-year after the construction boom, but occupancy remains above 92% metro-wide. The $1.7 billion Texas Instruments fab in Sherman and continued expansion along the I-35 corridor are creating new investment opportunities in northern suburbs.`,
    investment_tips: `For CRE syndication, DFW's sweet spot is value-add multifamily in the mid-cities (Arlington, Grand Prairie, Irving) where Class B/C properties trade at 5.5–6.5% cap rates with significant rent upside through renovations. Avoid over-leveraged deals in Frisco/Prosper where new supply is heaviest — these submarkets face 18–24 months of lease-up risk. Industrial investors should target last-mile logistics facilities near DFW Airport and the Alliance corridor in north Fort Worth.

Watch for rising property taxes — Collin and Denton counties have seen 8–12% annual assessment increases that can erode returns. Cap rate compression has largely stalled, so underwrite conservatively at 5.5%+ exit caps. The best syndication plays combine workforce housing (rents under $1,500) with operational improvements — DFW's job growth supports strong occupancy but renters are increasingly price-sensitive as supply catches up with demand.`
  },
  {
    name: "Austin, TX",
    slug: "austin",
    market_trends: `Austin's real estate market is in a corrective phase that's creating compelling entry points for disciplined investors. The median home price settled around $440,000 in Q4 2025, down roughly 18% from the 2022 peak of $550,000. Travis County median prices dipped nearly 2% year-over-year to $499,000 in December 2025, while sales volume increased 6.1%. Inventory has improved dramatically — months of supply now sits near 4.5 months, giving buyers substantial negotiating power not seen since pre-pandemic.

Despite the residential correction, Austin's economic engine remains powerful. The metro continues to attract major tech employers — Samsung's $17 billion chip fab in Taylor, Tesla's Gigafactory expansion, and Apple's $1 billion campus fuel a pipeline of 80,000+ tech workers. Multifamily has been the most impacted CRE sector, with over 30,000 new units delivered in 2024–2025 pushing vacancy to 10%+ and effective rents down 3–5% in some submarkets. However, this supply wave is now peaking, with new starts dropping 60% from the 2022 high.`,
    investment_tips: `Austin presents a rare buying window for patient syndication capital. Target distressed or motivated sellers in the multifamily space — properties that underwrote 2022-era rent assumptions are hitting the market at 15–20% discounts. The East Riverside corridor and Pflugerville/Round Rock offer the best value-add opportunities with cap rates stretching to 5.5–6.0%, compared to sub-5% just two years ago. Avoid luxury Class A multifamily where concessions are running 6–8 weeks free.

The industrial and life sciences sectors are Austin's bright spots for syndication. The semiconductor corridor along SH-130 is creating demand for flex/industrial space, and lab space vacancy is near zero. For residential syndication, focus on build-to-rent communities in Hutto, Georgetown, and Kyle where affordability drives demand. Key risk: Austin's property tax rates (~2.2%) are among the highest in the nation and can significantly impact cash-on-cash returns — stress test every deal at current assessment levels plus 5–8% annual increases.`
  },
  {
    name: "Nashville, TN",
    slug: "nashville",
    market_trends: `Nashville's real estate market showed resilience in 2025 with total home sales of 33,737, essentially flat compared to 2024's 33,935 closings. The median home price reached $475,000, up 0.9% year-over-year, reflecting a market that has stabilized after years of double-digit growth. Nashville remains a somewhat competitive market with a Redfin score of 32/100, indicating opportunity for buyers. The healthcare sector continues to anchor the economy — HCA Healthcare, Community Health Systems, and over 500 healthcare companies create a recession-resistant employment base.

Commercial real estate is benefiting from Nashville's emergence as a top-5 corporate relocation destination. Oracle's $1.2 billion campus in East Nashville is under construction, Amazon's operations hub continues to expand, and AllianceBernstein's headquarters relocation has brought hundreds of financial services jobs. Multifamily fundamentals are healthy with metro-wide occupancy around 93%, though the SoBro/Gulch submarket faces new supply pressure with 5,000+ units in the pipeline. Industrial vacancy remains tight at under 4% driven by e-commerce and distribution demand.`,
    investment_tips: `Nashville syndication plays should focus on suburban multifamily in Murfreesboro, Mt. Juliet, and Hendersonville where population growth is strongest and cap rates run 5.5–6.5% on value-add deals. The urban core (SoBro, Germantown) commands premium pricing at 4.5–5.0% caps that leave little margin for error. Look for properties near the planned transit corridors — Nashville's transportation infrastructure investment will drive long-term appreciation.

Workforce housing is the most undersupplied segment — Nashville needs an estimated 20,000+ affordable units. Syndications targeting properties at $1,100–$1,400/month rents with light renovation programs consistently outperform. Watch insurance costs carefully: Tennessee has seen 15–25% premium increases in 2024–2025 that can blow up proformas. Industrial flex space along I-24 and I-65 corridors offers 7–8% yields with lower management intensity. Tennessee's lack of state income tax remains a powerful draw for both residents and investors.`
  },
  {
    name: "Phoenix, AZ",
    slug: "phoenix",
    market_trends: `Phoenix's housing market outpaced national trends again in 2025, with the median single-family home price matching the national average at $480,000. Year-over-year price changes have been mixed — some periods showing a slight 0.4% dip, while overall 2025 appreciation tracked around 3–5% depending on the submarket. The metro continues to benefit from massive semiconductor investment, with TSMC's $40 billion fab complex in north Phoenix and Intel's $20 billion expansion in Chandler creating a new "Silicon Desert" tech corridor.

Phoenix's commercial real estate market is bifurcated. Industrial is the star performer with vacancy below 5% and asking rents up 8–12% year-over-year, driven by reshoring and nearshoring trends. Multifamily faces headwinds from oversupply — roughly 25,000 new units were delivered in 2024–2025, pushing vacancy above 9% in some submarkets and flattening rent growth. Office continues its slow recovery, with Class A in Scottsdale/Tempe performing well while suburban Class B struggles with 18%+ vacancy. Population growth remains robust at 1.5% annually, ranking Phoenix among the top 3 fastest-growing major metros.`,
    investment_tips: `Phoenix syndication investors should be selective about multifamily timing — the supply glut creates acquisition opportunities but near-term cash flow risk. Target 2015–2019 vintage Class B properties in Mesa, Gilbert, and Chandler near the semiconductor fabs, where worker housing demand will intensify through 2027. Cap rates for value-add multifamily have expanded to 5.5–6.0%, up 75–100 bps from 2022 — a healthier basis for new acquisitions.

Industrial is the highest-conviction play, particularly small-bay flex and last-mile distribution near Sky Harbor Airport and along the I-10/I-17 corridors. Cap rates run 6.0–7.0% with strong rent growth tailwinds. Key risks include water scarcity concerns (though largely overstated for urban Phoenix) and extreme heat driving up insurance and utility costs. For build-to-rent syndications, the west valley (Buckeye, Goodyear, Surprise) offers the best land basis, but infrastructure and HOA costs can eat into margins. Always stress test for rising property insurance — Arizona premiums have increased 20–30% since 2023.`
  },
  {
    name: "Atlanta, GA",
    slug: "atlanta",
    market_trends: `Atlanta's office market showed meaningful recovery in Q4 2025, with full-service asking rates hitting an all-time high of $33.30/SF, up 2.8% year-over-year. Vacancy declined 30 basis points quarter-over-quarter to 25.0%, the lowest in seven quarters. The flight-to-quality trend dominated 2025 leasing, with 73.5% of new activity in Trophy or Class A properties. New construction activity dropped to its lowest level since 2011, which will help the market rebalance over the next 18–24 months.

Atlanta's metro population surpassed 6.3 million in 2025, with the northern suburbs (Alpharetta, Johns Creek, Suwanee) and the BeltLine corridor driving the most growth. The film and entertainment industry continues to expand, earning Atlanta the "Hollywood of the South" moniker with $4.4 billion in annual economic impact. Industrial and logistics remain the market's backbone — Hartsfield-Jackson's cargo operations and the Savannah port's inland distribution network support sub-5% industrial vacancy. Multifamily rent growth moderated to 2–3% but occupancy held steady at 93%.`,
    investment_tips: `Atlanta offers some of the best risk-adjusted returns for CRE syndication in the Southeast. Value-add multifamily in the I-285 perimeter ring — particularly Clayton, DeKalb, and south Fulton counties — delivers 6.0–7.5% cap rates on acquisition with 200–400 bps of upside through renovations. These submarkets benefit from strong renter demand but haven't seen the institutional capital flood that compressed yields in Midtown and Buckhead.

For office syndication, focus exclusively on Class A/Trophy in Midtown and Buckhead where tenants are consolidating. Suburban office is a value trap — avoid it. Industrial investors should target infill locations inside I-285 where last-mile delivery demand is strongest and land constraints create pricing power. Atlanta's property tax assessments can be aggressive — budget 10–15% annual increases in Fulton County and actively protest assessments. The BeltLine's continued expansion (Southside Trail opening in 2026) creates rezoning and densification plays worth monitoring for longer-hold syndications.`
  },
  {
    name: "Tampa, FL",
    slug: "tampa",
    market_trends: `Tampa Bay's real estate market entered a corrective plateau in 2025, with the median home price settling around $370,000–$376,000, down approximately 4.2% year-over-year according to Zillow. Inventory has risen sharply, giving buyers more options than at any point since 2019. Homes are going to pending in about 25 days, indicating a shift from the frenzied seller's market of 2021–2022 to a more balanced environment. Mortgage rate sensitivity is a major factor — Tampa's market moves more with rates than most metros.

Despite the residential correction, Tampa's commercial fundamentals remain solid. The metro added 45,000+ jobs in 2025, led by healthcare (Tampa General, AdventHealth), financial services (USAA, JPMorgan), and tech. Water Street Tampa, the $3.5 billion mixed-use development by Jeff Vinik and Cascade Investment, continues to reshape the downtown core. Industrial vacancy sits below 5% with port-adjacent logistics driving demand. Florida's elimination of commercial lease sales tax (reduced from 4.5% to 2.0%) has boosted retail and office leasing activity significantly.`,
    investment_tips: `Tampa syndication investors should capitalize on the residential price correction — distressed multifamily and condo conversion opportunities are emerging as sellers who bought at 2022 peaks face negative equity. Target Class B multifamily in Brandon, Temple Terrace, and the I-75 corridor where cap rates have expanded to 5.5–6.5%. Waterfront and flood-zone properties require careful underwriting — insurance costs have doubled or tripled in some cases, making many deals untenable.

The strongest risk-adjusted play is suburban industrial along the I-4/I-75 interchange and near Port Tampa Bay, where logistics demand supports 6.5–7.5% cap rates. Retail strip centers anchored by essential services are performing well in fast-growing suburbs like Wesley Chapel, Riverview, and Land O'Lakes. Critical risk factor: hurricane insurance and flood insurance costs are the single biggest variable that can break a Tampa deal — always get binding quotes before going hard on deposits. Properties outside flood zones in eastern Hillsborough and Pasco counties offer better insurance profiles.`
  },
  {
    name: "Charlotte, NC",
    slug: "charlotte",
    market_trends: `Charlotte's housing market showed steady growth in 2025, with the median home price reaching $443,850 in September 2025, a 3.24% year-over-year increase from $429,945. The market remains somewhat competitive with homes receiving about 2 offers on average and selling in around 80 days. Supply has improved, with months of inventory approaching 3.5 months — still favoring sellers but significantly more balanced than 2022's sub-1-month levels.

Charlotte's emergence as the nation's second-largest banking center after New York continues to drive CRE demand. Bank of America, Wells Fargo, and Truist collectively employ over 50,000 workers downtown, and the fintech sector is growing rapidly. The LYNX Silver Line light rail extension (under construction) will reshape the University City and east Charlotte corridors. Multifamily development has been concentrated along the Blue Line and in South End, where rents average $1,800–$2,200 for Class A units. Industrial demand remains exceptional, with Charlotte's inland port status and I-85/I-77 logistics corridors supporting 4% vacancy rates.`,
    investment_tips: `Charlotte syndication opportunities are strongest in the "Path of Progress" — the northeast corridor along I-85 toward Concord/Kannapolis and the south I-77 corridor toward Rock Hill, SC. Value-add multifamily in these areas trades at 5.5–6.5% cap rates with strong rent growth driven by population inflows from the Northeast and Midwest. The University City submarket near UNCC offers compelling workforce housing plays at below-market rents with renovation upside.

Industrial/logistics is Charlotte's highest-conviction CRE sector for syndication. The Northlake and Airport/West areas offer 6.5–7.5% cap rates on multi-tenant industrial with minimal downside risk. Avoid large speculative office investments — Charlotte's office vacancy is elevated at 17%+ and remote work has permanently reduced demand. For mixed-use plays, South End and NoDa continue to outperform, but entry pricing is steep at sub-5% caps. North Carolina's business-friendly tax environment (2.5% corporate rate, no state capital gains preference) enhances after-tax returns for syndication investors.`
  },
  {
    name: "Denver, CO",
    slug: "denver",
    market_trends: `Denver's housing market has undergone a meaningful correction, with the average home value at $558,705, down 3.6% year-over-year. The overall median home price in the metro sits around $599,000 for detached homes and $400,000 for attached. Inventory has expanded significantly, with active listings up 35% from 2024 and months of supply reaching 3.5 months. Homes go to pending in about 15 days, but price reductions are common — nearly 40% of listings have cut prices.

Denver's commercial real estate market reflects the broader Rocky Mountain region's adjustment. The tech sector has contracted modestly (layoffs at local offices of national firms), but aerospace/defense (Lockheed Martin, Ball Aerospace, United Launch Alliance) and renewable energy provide economic ballast. Multifamily has been the most pressured sector, with 15,000+ new units delivered in 2024–2025 pushing vacancy above 8% and effective rents declining 2–4% in downtown and RiNo. However, the construction pipeline is drying up fast — new starts are down 55% from the peak, suggesting a supply-demand rebalance by late 2026.`,
    investment_tips: `Denver presents a contrarian syndication opportunity — the negative sentiment has pushed cap rates for value-add multifamily to 5.5–6.5%, the widest spread over Treasuries in five years. Target the Aurora/I-225 corridor and Lakewood/Wheat Ridge where workforce housing demand remains strong and renovation upside is substantial. Avoid downtown luxury — concessions are running 8–10 weeks free and won't normalize until 2027.

Industrial remains Denver's strongest CRE sector, with the I-70/E-470 corridor and DIA-adjacent logistics parks commanding 6.0–6.5% cap rates with 4–6% annual rent escalations. For residential syndication, build-to-rent communities in the northern metro (Brighton, Frederick, Firestone) offer strong demand from families priced out of homeownership. Key risks: Colorado's new rent control legislation (passed in 2024) limits rent increases in some jurisdictions and may expand — factor this into long-term underwriting. Property taxes are also a wildcard after the 2023 TABOR complications. The legal cannabis industry creates unique opportunities for specialty industrial/retail spaces with cap rates of 8–12%.`
  },
  {
    name: "Raleigh, NC",
    slug: "raleigh",
    market_trends: `Raleigh's housing market demonstrated steady strength in 2025 despite some price per square foot softening (down 4.1% YoY per Redfin). Overall median prices increased approximately 2.5% year-over-year, supported by consistent demand from tech workers relocating to the Research Triangle. The market benefits from one of the most educated workforces in the nation — Duke, UNC, NC State, and Research Triangle Park create a deep talent pipeline that continues to attract corporate expansions.

The Research Triangle's commercial real estate market is driven by life sciences and technology. Apple's $1 billion campus in RTP, Google's engineering hub in Durham, and Epic Games' headquarters in Cary underpin office demand that outperforms most U.S. metros. Lab/R&D space vacancy is essentially zero, with rents for purpose-built life science space exceeding $45/SF NNN. Multifamily has seen significant new supply (8,000+ units delivered in 2024–2025) but absorption has been healthy at 85%+, supported by the Triangle's 2.5% annual population growth rate.`,
    investment_tips: `Raleigh syndication investors should focus on the I-540/Highway 55 corridor connecting RTP to Cary and Apex — this is ground zero for the Triangle's growth with median home prices still below $500,000 and Class B multifamily cap rates of 5.0–6.0%. The Holly Springs/Fuquay-Varina corridor to the south offers emerging market dynamics with 6.0–7.0% cap rates and strong population inflows.

Life sciences real estate is the highest-value syndication play in the Triangle but requires specialized knowledge — purpose-built lab space commands 50% rent premiums over traditional office. For more accessible deals, suburban retail and mixed-use in Wake Forest, Knightdale, and Wendell Falls offer 6.5–7.5% yields with population-driven demand growth. Risks include: Triangle property taxes are rising 5–8% annually, and new multifamily supply could pressure rents in downtown Raleigh and North Hills through mid-2026. North Carolina's pro-business environment and lack of rent control make it one of the most landlord-friendly states in the Southeast.`
  },
  {
    name: "Orlando, FL",
    slug: "orlando",
    market_trends: `Orlando's housing market is positioned for a strong 2025–2026 cycle, with projected increases of 15.2% in home sales and 12.1% in median home prices according to the Orlando Business Journal. The current median home price sits around $370,000 for single-family homes, with the median sale price per square foot at $245 (down 2.4% YoY per Redfin). The tourism economy — which generates $75 billion annually — provides a unique floor for real estate demand, with Disney, Universal, and the convention center employing 400,000+ workers who need housing.

Universal's Epic Universe theme park, opening in 2025, represents the largest theme park investment in decades and is catalyzing development across the International Drive corridor. Commercial real estate is responding — industrial vacancy is under 4% driven by e-commerce fulfillment, and retail vacancy has declined to 5% as tourism spending rebounds. Multifamily occupancy is strong at 94% with rents averaging $1,700 for Class A units. The SunRail commuter rail expansion and Brightline's planned Orlando-Tampa route are transportation catalysts reshaping suburban development patterns.`,
    investment_tips: `Orlando syndication plays fall into two categories: tourism-adjacent and growth-corridor. For tourism, short-term rental syndications near Disney (Kissimmee/Celebration) can generate 8–12% cash-on-cash returns but carry regulatory risk — Osceola County has tightened STR rules significantly. For conventional multifamily, target the Lake Nona/Medical City corridor where population growth exceeds 10% annually and Class B cap rates run 5.5–6.5%.

Industrial near Orlando International Airport and along the FL Turnpike is the most consistent performer, with 6.5–7.5% cap rates and minimal vacancy risk. The I-4 corridor between Orlando and Tampa is emerging as a major logistics hub. Avoid condo-hotel investments — these have historically underperformed in Orlando due to high HOA fees and seasonal occupancy fluctuations. Key risks: hurricane insurance (though Orlando's inland location provides better rates than coastal Florida) and property tax increases averaging 6–8% annually in Orange County. The upcoming Epic Universe opening creates a near-term catalyst for hospitality and retail syndications along International Drive.`
  },
  // TIER 2
  {
    name: "Houston, TX",
    slug: "houston",
    market_trends: `Houston's housing market remains one of the most affordable major metros in the U.S., with a median single-family home price of $335,000 — essentially flat year-over-year. Active listings surged 16.5% to 52,727 in December 2025, providing ample inventory for buyers. Single-family sales were up 2.8% for the month. The 12-month average median price has modestly declined from $336,000 to $332,000, reflecting a market finding its equilibrium after the post-pandemic run-up.

Houston's economy has successfully diversified beyond energy — the Texas Medical Center (the world's largest) employs 106,000+ people, and the Port of Houston handles more foreign tonnage than any other U.S. port. CRE cap rates average 6.5% for multifamily, notably higher than DFW's 5.7%. The energy transition is creating new demand for industrial and office space from renewable energy firms, carbon capture companies, and hydrogen technology startups. Multifamily construction has slowed significantly from 2023 peaks, with new starts down 40%, setting up a tighter supply environment by 2027.`,
    investment_tips: `Houston is a cash flow market, not an appreciation play — syndication underwriting should prioritize Day 1 cash-on-cash returns of 6–8% rather than speculative upside. The best value-add multifamily opportunities are in the Energy Corridor (recovering from the 2020 downturn), Katy, and Pearland, where cap rates of 6.0–7.5% are available on 1990s–2000s vintage properties. The Heights/Montrose/EaDo corridor has gentrified significantly and now trades at tighter 5.0–5.5% caps.

Industrial is Houston's standout CRE sector — the ship channel corridor and northwest Houston (Highway 290/US 249) offer 7.0–8.5% cap rates on multi-tenant properties with strong demand from petrochemical, manufacturing, and distribution tenants. Key Houston-specific risks: flooding (always verify FEMA zone status and secure adequate flood insurance), energy sector cyclicality, and property tax rates that can exceed 2.5% in some jurisdictions. The Medical Center submarket (Braeswood/Meyerland) offers recession-resistant tenant demand for both residential and medical office syndications.`
  },
  {
    name: "San Antonio, TX",
    slug: "san-antonio",
    market_trends: `San Antonio stands out as one of the most affordable major Texas metros, with a median home price around $297,000–$310,000, showing modest 2% year-over-year growth. The average home value of $256,363 per Zillow (down 3.9% YoY) reflects the broader Texas adjustment. Homes go to pending in about 34 days, indicating a balanced market. San Antonio's military presence (Joint Base San Antonio is the largest in the DoD) provides exceptional economic stability, with over 80,000 military and civilian jobs.

The city's commercial real estate market is evolving rapidly. Toyota's manufacturing plant expansion, the growing cybersecurity sector anchored by the NSA's Texas Cryptologic Center, and a thriving biosciences corridor are diversifying the economy beyond military and tourism. Multifamily development has been concentrated along the I-35 corridor and in the rapidly growing far north side (Stone Oak, TPC Parkway). Industrial vacancy is tight at 5.5% with particular strength in southeast San Antonio near the Toyota plant and distribution facilities.`,
    investment_tips: `San Antonio is arguably the best entry point for first-time syndication investors in Texas — lower basis, higher cap rates (6.0–7.5% for value-add multifamily), and a stable, military-driven tenant base. The northeast side (Converse, Live Oak, Universal City) near JBSA-Randolph offers the most recession-resistant rental demand in the state. The far west side (Alamo Ranch, Potranco corridor) is the fastest-growing submarket with strong build-to-rent potential.

For CRE syndication, target Class B/C multifamily along the US-281 and Loop 1604 corridors — these properties benefit from population growth without the institutional competition found in Dallas and Austin. Industrial along the I-35 South corridor between San Antonio and Laredo benefits from the nearshoring trend and cross-border trade. Avoid downtown office — San Antonio's office market has the highest vacancy rate among major Texas metros at 22%+. Key advantage: San Antonio's property taxes, while high by national standards (~2.3%), are lower than Austin or Dallas, improving net operating income margins.`
  },
  {
    name: "Jacksonville, FL",
    slug: "jacksonville",
    market_trends: `Jacksonville's median home price reached $308,000 in December 2025, reflecting remarkable 50%+ appreciation from pre-pandemic levels. Year-over-year, prices are essentially flat (up 0.002% per Redfin), indicating the market has found a sustainable price plateau. Homes receive about 2 offers on average and sell in approximately 83 days. Jacksonville's position as the largest city by land area in the continental U.S. provides extensive development options that naturally moderate price extremes.

The city's economy is powered by financial services (FIS, Black Knight/ICE, Deutsche Bank), logistics (JAXPORT's $1 billion+ expansion), and the U.S. Navy (NAS Jacksonville, Mayport). Population growth continues at 1.8% annually, making it one of Florida's fastest-growing large metros. Commercial real estate fundamentals are strong — industrial vacancy is under 4% driven by port logistics, and multifamily occupancy sits at 94% with rents averaging $1,450 for Class A units. The $2.5 billion Lot J development near the stadium is transforming downtown's riverfront.`,
    investment_tips: `Jacksonville offers the best value proposition in Florida for CRE syndication — similar growth dynamics to Tampa and Orlando but at a 20–30% price discount. Value-add multifamily on the Westside (Argyle Forest, Orange Park) and Southside/Baymeadows delivers 6.0–7.5% cap rates with strong military and healthcare tenant demand. The Beaches corridor (Jacksonville Beach, Neptune Beach) commands premium rents but trades at tighter 5.0–5.5% caps.

JAXPORT's expansion creates a compelling industrial syndication thesis — warehouse and distribution space within 15 miles of the port is the highest-demand segment. Target 10,000–50,000 SF multi-tenant industrial buildings in the Imeson/North Jacksonville corridor for 7.0–8.5% cap rates. Key risks: flood insurance costs (Jacksonville has significant flood zone exposure, particularly along the St. Johns River) and hurricane risk. Avoid St. Johns County for syndication unless targeting luxury — entry prices there have risen above $500,000 and cap rates are compressed. Jacksonville's lack of state income tax and relatively low cost of living make it an increasingly popular relocation destination from the Northeast.`
  },
  {
    name: "Miami, FL",
    slug: "miami",
    market_trends: `Miami's real estate market remains one of the most dynamic and expensive in the Southeast, driven by international capital flows, wealth migration from high-tax states, and its position as the gateway to Latin America. The median rent sits around $3,000/month (down 6.2% YoY), reflecting a multifamily market adjusting to significant new supply. Multifamily cap rates hover around 5.5%, slightly above the national average of 5.2%. Industrial asking rents have reached approximately $21/SF/year, supported by e-commerce, logistics, and trade activity tied to PortMiami and Miami International Airport.

The economy continues to diversify, with a projected 2.4% increase in total employment adding 80,000 new jobs in 2025. Florida's reduction of commercial lease sales tax from 4.5% to 2.0% has been a significant catalyst for retail and office leasing. Miami's office market is one of the few nationally experiencing positive absorption, driven by hedge funds, family offices, and tech firms relocating from New York and San Francisco. Brickell and Wynwood are the hottest submarkets, with Class A office rents exceeding $80/SF.`,
    investment_tips: `Miami syndication requires a different playbook than other Sunbelt markets — higher entry costs demand premium returns or strong appreciation theses. For multifamily, look at the rent correction as an opportunity — workforce housing in Hialeah, Doral, and Homestead offers 5.5–6.5% cap rates with a largely underserved renter base. Avoid luxury condo syndications where supply is excessive and carrying costs are punitive.

Industrial near Miami International Airport and the Medley/Hialeah warehouse corridor is the highest-conviction play, with cap rates of 5.5–6.5% and irreplaceable infill locations. Retail in Little Havana and Wynwood continues to appreciate as these neighborhoods gentrify. Critical Miami-specific risks: insurance costs are the single biggest deal-killer — wind/flood insurance can run $3,000–$8,000+ per unit annually and is rising 15–25% per year. Sea level rise is a long-term concern for waterfront properties — institutional buyers are already pricing this in. Factor in higher management costs (bilingual staff requirements) and aggressive property tax assessments in Miami-Dade County.`
  },
  {
    name: "Las Vegas, NV",
    slug: "las-vegas",
    market_trends: `Las Vegas' housing market has transitioned to a balanced state, with the median single-family price hovering near $470,000–$474,000 (down approximately 2% YoY). Inventory has surged 31% year-over-year, days on market have stretched to 55, and cash buyers still drive 23% of transactions. Condo/townhome supply jumped 47.9%. The market is cooling into a healthier equilibrium after the pandemic-era frenzy that saw prices nearly double.

Las Vegas' economy has diversified significantly beyond gaming and tourism. The Raiders' Allegiant Stadium, the Formula 1 Grand Prix (generating $1.5 billion in economic impact), and the upcoming A's baseball stadium are transforming the sports and entertainment landscape. The Las Vegas Convention Center's $1 billion expansion supports the MICE (meetings, incentives, conferences, exhibitions) industry. Healthcare (expanding HCA and Intermountain presence), logistics (I-11 corridor to Phoenix), and data centers (Switch's massive campus) add economic resilience. Multifamily occupancy remains strong at 93% with average rents around $1,500.`,
    investment_tips: `Las Vegas offers compelling value-add multifamily opportunities as the market cools. Target properties in the Henderson/Green Valley corridor and the southwest (Summerlin South, Enterprise) where cap rates run 5.5–6.5% and the tenant base skews toward healthcare and professional services workers rather than gaming industry employees. Avoid properties heavily dependent on Strip worker tenancy — these are cyclical and vulnerable to automation trends in hospitality.

Industrial along the I-15/I-215 corridors is Las Vegas' strongest CRE play, with cap rates of 6.5–7.5% and demand driven by California overflow logistics. The new I-11 corridor to Phoenix is creating a new logistics sub-market worth watching. Short-term rental syndications near the Strip can generate 10–15% gross yields but face increasing regulation from Clark County. Key risks: water scarcity (Lake Mead levels, though improved, remain a long-term concern), extreme heat driving utility costs, and gaming industry concentration. Nevada's lack of state income tax and corporate tax makes it attractive for out-of-state syndicators structuring pass-through returns.`
  },
  {
    name: "Salt Lake City, UT",
    slug: "salt-lake-city",
    market_trends: `Salt Lake City's real estate market showed notable strength in late 2025, with the median single-family sales price reaching $642,500 in November 2025, a 3.4% year-over-year increase. Redfin data showed even stronger recent momentum with the median sale price at $610,000, up 15.1% — though this likely reflects seasonal mix shifts. Inventory improved to 2.6 months of supply (up 30.4% YoY), providing more buyer options. The average home value of $571,928 is up 1.4% per Zillow.

Salt Lake City's "Silicon Slopes" tech corridor continues to drive economic growth, with companies like Qualtrics, Pluralsight, and Domo expanding alongside major tech firms' Utah offices. The 2034 Winter Olympics (awarded to Salt Lake City) are catalyzing major infrastructure investments including transit expansion, venue upgrades, and hotel development. Utah's population growth of 1.5% annually is among the highest in the nation, driven by both in-migration and the state's high birth rate. Commercial real estate benefits from this growth — multifamily occupancy is 94%+ and industrial vacancy is below 3%.`,
    investment_tips: `Salt Lake City syndication is a growth play — entry prices are higher than most Sunbelt markets, but Utah's demographic tailwinds and economic diversification support strong appreciation. Value-add multifamily in West Valley City, Murray, and Midvale offers the best cap rates (5.0–6.0%) within the metro, while Draper/Lehi in the Silicon Slopes corridor commands premium pricing at 4.5–5.0% caps.

The 2034 Olympics thesis is real — properties along the TRAX/FrontRunner transit lines will appreciate as infrastructure investments accelerate. Industrial in the northwest quadrant (Salt Lake City International Airport area) and along I-15 in Davis County offers 6.0–7.0% cap rates. Unique Utah consideration: the dominant LDS culture creates consistently high housing demand (larger family sizes) and below-average crime rates that enhance property values. Key risks: Utah's tight land availability (hemmed in by mountains) limits development but also constrains supply, supporting prices. Water rights and drought concerns are increasingly factored into development decisions. State regulations are landlord-friendly with no rent control.`
  },
  {
    name: "Columbus, OH",
    slug: "columbus",
    market_trends: `Columbus posted a strong finish to 2025, with December residential sales up 5.6% year-over-year to 2,291 closed transactions and a median sales price of $322,000. The median sale price per square foot is $184 (down just 0.81% YoY per Redfin). Columbus' economy is being transformed by Intel's $20 billion semiconductor fab in New Albany — the largest private investment in Ohio history — which is expected to create 3,000 direct jobs and 10,000+ indirect positions.

Beyond Intel, Columbus benefits from a diversified economy anchored by Ohio State University (one of the nation's largest employers), Nationwide Insurance, JPMorgan Chase's growing tech hub, and a thriving logistics sector. Honda's $3.5 billion EV battery plant in Fayette County adds to the manufacturing renaissance. Columbus' central Ohio location provides same-day truck delivery to 60% of the U.S. and Canadian population, making it a premier logistics hub. Multifamily fundamentals are healthy with 93% occupancy and average rents of $1,300 — well below coastal markets but sufficient to support attractive yields at Columbus' cost basis.`,
    investment_tips: `Columbus is an under-the-radar syndication market that offers Midwest stability with Sunbelt-like growth dynamics. The Intel/New Albany corridor is the obvious play — multifamily and build-to-rent within a 20-minute commute of the fab site will see outsized demand through 2028 as workers arrive. Cap rates for value-add multifamily run 6.0–7.5% in the northeast suburbs, the widest in any metro experiencing this level of investment.

Industrial is Columbus' anchor CRE asset class — the Rickenbacker Logistics Park area delivers 7.0–8.5% cap rates with blue-chip tenant demand from Amazon, FedEx, and hundreds of third-party logistics firms. The Short North, German Village, and Franklinton neighborhoods offer appreciation-oriented plays as Columbus' urban core continues to gentrify rapidly. Key advantages: Ohio has no rent control, property taxes are moderate (effective rate ~1.6%), and operating costs are significantly below coastal markets. Risk to watch: Columbus' multifamily supply pipeline is elevated with 8,000+ units under construction — time entries to avoid lease-up competition.`
  },
  {
    name: "Indianapolis, IN",
    slug: "indianapolis",
    market_trends: `Indianapolis remains one of the most affordable major metros for real estate investment, with the statewide median home price around $255,000 and the metro area slightly higher. Broad Ripple, a perennial favorite for young professionals, sees median prices of $325,000–$345,000. Indiana as a whole experienced a 5.7% year-over-year price increase in 2025, reflecting steady demand without the boom-bust volatility seen in Sunbelt markets.

Indianapolis' economy is uniquely diversified across life sciences (Eli Lilly's $3.7 billion investment, Roche Diagnostics), motorsports (Indianapolis Motor Speedway ecosystem), logistics (FedEx Ground's largest hub), and technology (Salesforce Tower, a growing tech scene). Eli Lilly's massive expansion — the largest pharmaceutical investment in U.S. history — is transforming the city's south side and Lebanon, IN with thousands of high-paying manufacturing and R&D jobs. Downtown Indianapolis has seen $8 billion in development investment over the past decade, and the cultural/sports amenities continue to attract millennial and Gen Z talent.`,
    investment_tips: `Indianapolis is the quintessential cash flow syndication market. Value-add multifamily on the east side (Irvington, Warren Township) and near the Lilly campus in Lebanon/Whitestown offers 7.0–8.5% cap rates — among the highest in any top-50 metro. The Broad Ripple/Meridian-Kessler corridor delivers lower yields (5.5–6.5%) but stronger appreciation and tenant quality. Fountain Square and the near-east side are gentrifying rapidly and offer repositioning opportunities.

Industrial along the I-70/I-65 corridors is Indianapolis' most consistent performer for syndication — the city's central U.S. location and FedEx hub create reliable demand with 7.0–9.0% cap rates on multi-tenant buildings. Key advantage: Indiana's overall cost of doing business is among the lowest in the nation, with a 3.23% flat income tax, no inventory tax, and reasonable property assessments. The Eli Lilly expansion is a once-in-a-generation catalyst — syndications targeting workforce housing within 30 minutes of the Lebanon campus should see outsized demand for the next 5–7 years. Risk: Indianapolis has elevated crime in certain pockets — thorough neighborhood-level due diligence is essential.`
  },
  {
    name: "Scottsdale, AZ",
    slug: "scottsdale",
    market_trends: `Scottsdale occupies the luxury tier of the Phoenix metro market, with a median sale price of $925,000 (down 8.6% YoY per Redfin) and a median price per square foot of $419. The market is somewhat competitive with homes receiving about 1 offer on average and selling in 80 days. Over the past decade, Scottsdale has seen the median home price rise to approximately $900,000, showcasing steady appreciation driven by wealth migration from California and the Northeast.

Scottsdale's economy is driven by tourism/hospitality (top U.S. resort destination), healthcare (Mayo Clinic, HonorHealth), technology, and financial services. The Scottsdale Airpark is one of the largest employment centers in Arizona, housing 2,700+ businesses and 50,000+ workers. Luxury retail and dining along the Scottsdale Road corridor continues to expand. The commercial market benefits from high barriers to entry — limited developable land and strict zoning keep supply constrained. Multifamily in Scottsdale commands premium rents of $2,200–$3,500 for Class A units, with occupancy above 95% for well-located properties.`,
    investment_tips: `Scottsdale syndication is inherently a luxury/high-net-worth play. The recent 8.6% price correction creates a compelling entry point for investors who believe in the long-term wealth migration thesis. Focus on the Old Town/Waterfront area for mixed-use and boutique hospitality syndications where tourism drives premium NOI. South Scottsdale offers relative value with median prices 40% below north Scottsdale and strong millennial renter demand.

For CRE, medical office near Mayo Clinic and HonorHealth campuses delivers 6.0–7.0% cap rates with recession-resistant tenant bases. Boutique hospitality (10–50 room properties) is an emerging syndication niche that capitalizes on Scottsdale's $5 billion tourism industry. Avoid speculative luxury condo development — the market is sensitive to economic cycles. Key risks: water scarcity (Scottsdale has been proactive with recycled water but long-term supply is a concern), high entry prices that limit return potential, and seasonal demand fluctuations that impact hospitality and short-term rental income. The Scottsdale Airpark area offers the best office investment fundamentals with lower vacancy than the Phoenix metro average.`
  },
  {
    name: "Boise, ID",
    slug: "boise",
    market_trends: `Boise's housing market has stabilized after its dramatic pandemic-era boom and subsequent correction. The average home value is $502,667 (up 0.8% YoY per Zillow), and Canyon County (the more affordable Nampa/Caldwell suburbs) saw stronger 6.4% appreciation with median prices reaching $435,000. Homes go to pending in about 9 days, indicating persistent demand. Boise's 2025 median price is forecast to increase modestly by 3%, with a further 4% gain expected in 2026.

Boise's economy has transformed from agriculture-dependent to a diversified technology and manufacturing hub. Micron Technology's $15 billion memory chip fab expansion (supported by CHIPS Act funding) is the state's largest-ever private investment. HP Inc., Albertsons Companies (headquartered in Boise), and a growing fintech/SaaS startup scene provide economic breadth. Idaho's population growth of 1.9% annually consistently ranks top-5 nationally, driven by Californians and Pacific Northwesterners seeking affordability and quality of life. Commercial real estate remains undersupplied — multifamily vacancy is below 5% and industrial vacancy is under 3%.`,
    investment_tips: `Boise is a growth-oriented syndication market where the play is capturing population-driven demand. Value-add multifamily in Meridian and Nampa offers the best risk-adjusted returns at 5.5–6.5% cap rates. The Micron expansion corridor along Chinden/State Street will see significant housing demand over the next 3–5 years. Build-to-rent is particularly compelling in Star, Eagle, and Kuna where single-family rental demand exceeds supply.

Industrial in the Boise Airport area and along I-84 in Caldwell/Nampa delivers 6.5–7.5% cap rates and benefits from Idaho's low operating costs and business-friendly environment. Boise's downtown core is undergoing a development boom with mixed-use projects, but entry pricing is steep at sub-5% caps. Key advantages: Idaho has no corporate income tax for pass-through entities (as of 2023), property taxes are low (~0.6% effective rate), and the regulatory environment is extremely landlord-friendly. Risks: Boise is a smaller market ($5 billion total CRE inventory) which limits exit options — always underwrite for a 5–7 year hold with limited buyer pool assumptions. Water rights in Idaho are a real consideration for any development-oriented syndication.`
  },
  // TIER 3
  {
    name: "Huntsville, AL",
    slug: "huntsville",
    market_trends: `Huntsville is one of America's most compelling emerging markets for CRE investment. The median home price sits around $322,000–$344,000 (Redfin shows $322K, down 0.92% YoY; Movoto reports $344K in October 2025), with the Huntsville submarket specifically up 2% to $327,000. Sales volume jumped 13.4% year-over-year, signaling strong underlying demand. The median price per square foot of $165 (up 1.9% YoY) reflects the market's continued value proposition relative to national averages.

Huntsville's economy is powered by the U.S. Army's Redstone Arsenal, NASA's Marshall Space Flight Center, and a growing constellation of defense and aerospace contractors — Lockheed Martin, Boeing, Raytheon, and Blue Origin all have major facilities. The FBI's new $1.4 billion campus (operational 2025) is adding 4,000+ federal jobs. Mazda-Toyota's $2.3 billion manufacturing plant in north Huntsville employs 4,000+ workers. The metro's population surpassed 500,000 in 2024, having grown 16% in the past decade. This military-tech-manufacturing trifecta creates one of the most recession-resistant economies in the Southeast.`,
    investment_tips: `Huntsville offers the highest cap rates of any rapidly growing U.S. metro — value-add multifamily trades at 6.5–8.0%, a significant premium over comparable growth markets. Target properties in the Research Park/Bridge Street corridor and along US-72 in Madison where defense/tech worker demand is concentrated. The south Huntsville corridor near Redstone Arsenal offers recession-proof tenant demand that institutional investors haven't yet discovered at scale.

Industrial near the Jetplex Industrial Park and along I-565 offers 7.5–9.0% cap rates with demand driven by automotive (Mazda-Toyota supply chain), aerospace, and defense logistics. For residential syndication, build-to-rent in the fast-growing Meridianville/Toney area north of the city offers strong demand at attainable price points. Key advantages: Alabama's property taxes are among the lowest in the nation (~0.4% effective rate), dramatically improving cash-on-cash returns vs. Texas or Florida. There's no state-level rent control and the regulatory environment is exceptionally landlord-friendly. Risk: Huntsville is a smaller market, so exit liquidity is limited — plan for 5–7 year holds and conservative exit cap rate assumptions.`
  },
  {
    name: "Knoxville, TN",
    slug: "knoxville",
    market_trends: `Knoxville's housing market experienced some price softening in 2025, with the median sale price declining 4.1% year-over-year to $319,000 per Redfin, while Zillow reports the average home value at $368,490 (up 0.8% YoY). The median price per square foot of $220 declined 1.1% YoY. This divergence reflects a market adjusting from post-pandemic peaks — Knoxville saw massive appreciation from 2020–2023 as remote workers discovered east Tennessee's combination of Smoky Mountain access, low cost of living, and no state income tax.

Knoxville's economy is anchored by the University of Tennessee (30,000+ students, major employer), Oak Ridge National Laboratory (the DOE's largest science and energy lab), and a growing healthcare sector (Covenant Health, University of Tennessee Medical Center). The Y-12 National Security Complex and Oak Ridge provide a stable federal employment base. Downtown Knoxville has undergone a remarkable revitalization — Market Square and the Old City districts now feature vibrant restaurant, brewery, and retail scenes that attract young professionals. Tourism revenue from the Smoky Mountains ($3 billion+ annually) provides additional economic support.`,
    investment_tips: `Knoxville's price correction makes it an attractive entry point for syndication investors. Value-add multifamily in the Bearden/West Knoxville corridor and near UT's campus offers 6.5–7.5% cap rates. Student housing near the university is a specialized but reliable niche — Knoxville's 30,000+ student population creates consistent demand for purpose-built housing at premium per-bed rents.

Short-term rental syndications targeting Smoky Mountain tourism are a unique opportunity — Sevier County (Gatlinburg/Pigeon Forge) generates $3 billion annually in tourism revenue. Properties within 30 minutes of Dollywood can yield 10–15% gross returns, though regulatory and management complexity is higher. For conventional CRE, industrial along the I-40/I-75 intersection offers 7.0–8.5% cap rates. Knoxville's position as a logistics crossroads (Atlanta, Nashville, Charlotte, and the Midwest are all within a day's drive) supports distribution demand. Tennessee's no-income-tax advantage applies to both residents and syndication investors, enhancing after-tax returns. Risk: Knoxville is a tertiary market with limited institutional buyer demand — underwrite conservatively on exits.`
  },
  {
    name: "Greenville, SC",
    slug: "greenville-sc",
    market_trends: `Greenville's real estate market has matured significantly, with the median sale price reaching $443,000 (down 0.45% YoY per Redfin) while the average home value sits at $325,904 (up 0.6% per Zillow). At $475,000 in some measures, Greenville's median tops the projected national median of $410,700 yet remains well below coastal South Carolina peers like Charleston. The median price per square foot of $283 declined 7.2% YoY, suggesting some softening in the higher end of the market.

Greenville's economic transformation over the past two decades has been remarkable. BMW's massive manufacturing plant in nearby Spartanburg (the largest BMW factory in the world) anchors a robust automotive corridor along I-85. Michelin North America's headquarters, GE Power's gas turbine manufacturing, and a burgeoning health sciences sector (Prisma Health) provide economic diversity. Downtown Greenville's Falls Park and Main Street revitalization is frequently cited as one of the best urban redevelopment stories in the U.S. The Greenville-Spartanburg-Anderson metro population reached 1.1 million and continues growing at 1.5% annually.`,
    investment_tips: `Greenville syndication benefits from the I-85 corridor between Charlotte and Atlanta — a 350-mile stretch that's one of the fastest-growing economic corridors in the country. Value-add multifamily in Mauldin, Simpsonville, and Taylors offers 6.0–7.5% cap rates with strong demand from BMW and Michelin employees. The Verdae/Patewood corridor near the medical district commands premium rents but cap rates are compressed to 5.0–5.5%.

Industrial along I-85 and in the Inland Port area (Greer) is Greenville's highest-conviction CRE play, with 7.0–8.5% cap rates and demand supported by the automotive supply chain and e-commerce distribution. South Carolina's Port of Charleston feeds inland distribution through Greenville's inland port, creating a unique logistics advantage. Mixed-use and boutique hospitality in downtown Greenville benefit from the city's growing tourism and corporate meeting industry. Key advantages: South Carolina has moderate property taxes (~0.6% effective rate), no state-level rent control, and generous tax incentives for commercial investment. Risk: Greenville is increasingly discovered — institutional capital is arriving, which compresses cap rates but also improves exit liquidity.`
  },
  {
    name: "Chattanooga, TN",
    slug: "chattanooga",
    market_trends: `Chattanooga's average home value stands at approximately $327,900 (essentially flat YoY per Zillow), while Hamilton County median prices showed stronger performance, jumping 9–10% YoY to $365,000 in late 2024/early 2025. The median price per square foot of $198 is up 1.5% YoY per Redfin. Chattanooga remains significantly more affordable than Nashville (nearly 30% lower median prices), positioning it as an attractive alternative for both residents and investors priced out of larger Tennessee metros.

Chattanooga gained national attention for its municipal gigabit internet (EPB Fiber Optics), which has catalyzed a tech startup ecosystem and attracted remote workers. Volkswagen's $800 million investment in EV production at its Chattanooga plant, plus the adjacent SK Innovation battery plant, positions the city as a major EV manufacturing hub. The outdoor recreation economy (Lookout Mountain, Tennessee River, Rock City) supports a growing tourism sector that drives hospitality and retail demand. Amazon's 3.6 million SF fulfillment center and a growing logistics sector benefit from Chattanooga's crossroads position at I-24 and I-75.`,
    investment_tips: `Chattanooga is an emerging syndication market offering tertiary-market cap rates with secondary-market growth dynamics. Value-add multifamily in the Hixson/Red Bank corridor and East Brainerd/Ooltewah offers 6.5–8.0% cap rates — significantly higher than Nashville for a city just 130 miles southeast. The Southside and North Shore neighborhoods adjacent to downtown are gentrifying rapidly and offer appreciation-oriented plays with renovation upside.

Industrial near the Enterprise South Industrial Park (VW/SK Innovation area) and along the I-75 corridor delivers 7.5–9.0% cap rates with demand anchored by automotive manufacturing, logistics, and Amazon operations. Student housing near UTC (University of Tennessee at Chattanooga) offers a specialized niche. Chattanooga's gigabit internet is a genuine differentiator — it attracts tech-oriented tenants willing to pay rent premiums. Key advantages: Tennessee's no income tax, Alabama's proximity (offering even lower-cost labor pools), and Chattanooga's growing quality of life. Risk: this is a smaller market (~600,000 metro population) — exit options are limited to a smaller buyer pool. Budget for longer hold periods (5–7 years) and conservative exit cap assumptions.`
  },
  {
    name: "Tucson, AZ",
    slug: "tucson",
    market_trends: `Tucson's housing market showed modest softening in 2025, with the median price decreasing 0.9% year-over-year to $356,750 while the average price increased 2.1% to $424,599. Zillow reports the average home value at $332,818 (down 1.8% YoY). Active listings reached 4,911 by September 2025, providing healthy inventory levels. The median price per square foot of $207 is down 2.8% YoY per Redfin. Tucson remains significantly more affordable than Phoenix (roughly 30% lower median prices), making it attractive for investors seeking Arizona exposure at a lower basis.

Tucson's economy is driven by the University of Arizona (the city's largest employer with 13,000+ staff), Raytheon Missiles & Defense (16,000+ employees and expanding), and a growing biosciences sector. Davis-Monthan Air Force Base provides stable military employment. The Rillito/Oracle corridor is seeing significant redevelopment, and the streetcar line connecting downtown to the university has catalyzed urban infill. Tucson's tech sector is growing with drone technology (now designated as the U.S. Drone Capital), optics/photonics, and mining technology companies. The metro's population of 1.05 million grows at about 1% annually.`,
    investment_tips: `Tucson offers the lowest entry point of any Arizona market for CRE syndication. Value-add multifamily near the University of Arizona (Sam Hughes, Iron Horse, Armory Park neighborhoods) delivers 6.5–8.0% cap rates with strong student and young professional demand. The east side (Rita Ranch, Vail, Houghton corridor) is the fastest-growing residential area with build-to-rent potential.

Industrial near Tucson International Airport and the I-10 corridor offers 7.5–9.0% cap rates — Raytheon's continued expansion drives demand for defense-adjacent industrial and flex space. The downtown/4th Avenue district is experiencing a mini-renaissance with mixed-use development opportunities. Key advantages: entry pricing is 30–50% below Phoenix, Arizona has no rent control, and Raytheon's expansion provides recession-resistant demand. Risks: Tucson's market is smaller and less liquid than Phoenix, the economy is more concentrated (university + defense), and summer heat extremes impact utility costs and seasonal occupancy. Water availability is a longer-term concern — Tucson relies heavily on CAP (Central Arizona Project) water allocations. For syndication, focus on the east side and university corridor for the best combination of cash flow and appreciation potential.`
  }
];

async function main() {
  console.log('Deleting existing cities...');
  const { error: delError } = await supabase.from('cities').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (delError) {
    console.error('Delete error:', delError);
    return;
  }
  
  console.log(`Inserting ${cities.length} cities...`);
  
  // Insert in batches of 5
  for (let i = 0; i < cities.length; i += 5) {
    const batch = cities.slice(i, i + 5);
    const { data, error } = await supabase.from('cities').insert(batch).select('name');
    if (error) {
      console.error(`Error inserting batch ${i/5 + 1}:`, error);
    } else {
      console.log(`Batch ${i/5 + 1}: Inserted ${data.length} cities -`, data.map(c => c.name).join(', '));
    }
  }
  
  // Verify
  const { count, error: countError } = await supabase.from('cities').select('*', { count: 'exact', head: true });
  if (countError) {
    console.error('Count error:', countError);
  } else {
    console.log(`\nVerification: ${count} cities in the table`);
  }
  
  // List all
  const { data: all } = await supabase.from('cities').select('name, slug').order('name');
  console.log('\nAll cities:');
  all.forEach((c, i) => console.log(`  ${i+1}. ${c.name} (${c.slug})`));
}

main().catch(console.error);
