import React, { useState } from 'react';
import { Navbar } from '../../components/Navbar';
import { Footer } from '../../components/Footer';
import { Search, Book, Sparkles, Filter, ArrowRight, BookOpen } from 'lucide-react';

interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
}

const glossaryTerms: GlossaryTerm[] = [
  {
    term: "Accredited Investor",
    definition: "An individual who meets specific income or net worth requirements set by the SEC, allowing them to participate in certain private investment opportunities.",
    category: "Investor Qualifications"
  },
  {
    term: "Cap Rate",
    definition: "Capitalization rate; a property's net operating income divided by its market value, used to estimate and compare the rates of return on different real estate investments.",
    category: "Financial Metrics"
  },
  {
    term: "Cash-on-Cash Return",
    definition: "A rate of return that calculates the cash income earned on the cash invested in a property, calculated by dividing the annual cash flow by the total cash investment.",
    category: "Financial Metrics"
  },
  {
    term: "Due Diligence",
    definition: "The investigation or audit of a potential investment to confirm all material facts regarding the investment and assess potential risks.",
    category: "Investment Process"
  },
  {
    term: "Equity Multiple",
    definition: "The total return on investment, calculated by dividing the total cash distributions by the total cash invested.",
    category: "Financial Metrics"
  },
  {
    term: "General Partner (GP)",
    definition: "The sponsor or manager of a real estate investment who is responsible for executing the business plan and managing the investment.",
    category: "Investment Structure"
  },
  {
    term: "Internal Rate of Return (IRR)",
    definition: "A metric used to estimate the profitability of potential investments that accounts for the time value of money.",
    category: "Financial Metrics"
  },
  {
    term: "Limited Partner (LP)",
    definition: "An investor in a real estate deal who provides capital but has no involvement in day-to-day operations.",
    category: "Investment Structure"
  },
  {
    term: "Net Operating Income (NOI)",
    definition: "The annual income generated by a property after deducting operating expenses but before debt service and capital expenditures.",
    category: "Financial Metrics"
  },
  {
    term: "Preferred Return",
    definition: "A minimum return that limited partners must receive before the general partner can participate in profits.",
    category: "Investment Structure"
  },
  {
    term: "Private Placement Memorandum (PPM)",
    definition: "A legal document providing detailed information about an investment offering and the associated risks.",
    category: "Legal Documents"
  },
  {
    term: "Real Estate Syndication",
    definition: "A method of pooling capital from multiple investors to purchase and operate real estate that would be difficult to purchase or manage individually.",
    category: "Investment Structure"
  },
  {
    term: "Regulation D",
    definition: "SEC rules that allow companies to raise capital through the sale of equity or debt securities without registering with the SEC.",
    category: "Legal Documents"
  },
  {
    term: "Value-Add",
    definition: "An investment strategy that involves making improvements to a property to increase its value and potential returns.",
    category: "Investment Strategy"
  },
  {
    term: "Waterfall Distribution",
    definition: "A method of distributing profits among partners in a predetermined order, typically giving preference to limited partners up to a certain return.",
    category: "Investment Structure"
  },
  {
    term: "1031 Exchange",
    definition: "A tax-deferred exchange that allows an investor to sell a property and reinvest the proceeds in a new property while deferring capital gains taxes.",
    category: "Tax Strategy"
  },
  {
    term: "Bridge Loan",
    definition: "Short-term financing used until a long-term loan can be secured or the property is sold.",
    category: "Financing"
  },
  {
    term: "Capital Stack",
    definition: "The layers of capital that comprise the total funding of a real estate investment, including debt and various classes of equity.",
    category: "Investment Structure"
  },
  {
    term: "Debt Service Coverage Ratio (DSCR)",
    definition: "The ratio of net operating income to debt service, used to measure a property's ability to cover its debt payments.",
    category: "Financial Metrics"
  },
  {
    term: "Loan-to-Value Ratio (LTV)",
    definition: "The ratio of a loan amount to the value of the property securing the loan.",
    category: "Financial Metrics"
  },
];

export function Glossary() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');

  const categories = ['all', ...new Set(glossaryTerms.map(term => term.category))];

  const filteredTerms = glossaryTerms.filter(term => {
    const matchesSearch = term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         term.definition.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'all' || term.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const getCategoryColor = (category: string) => {
    const colors: Record<string, string> = {
      'Financial Metrics': 'bg-blue-100 text-blue-700',
      'Investment Structure': 'bg-purple-100 text-purple-700',
      'Tax Strategy': 'bg-emerald-100 text-emerald-700',
      'Legal Documents': 'bg-amber-100 text-amber-700',
      'Investment Strategy': 'bg-rose-100 text-rose-700',
      'Investment Process': 'bg-cyan-100 text-cyan-700',
      'Investor Qualifications': 'bg-indigo-100 text-indigo-700',
      'Financing': 'bg-orange-100 text-orange-700',
    };
    return colors[category] || 'bg-gray-100 text-gray-700';
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-purple-50">
      <Navbar />

      {/* Hero Header */}
      <div className="bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-700 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9IiNmZmZmZmYiIGZpbGwtb3BhY2l0eT0iMC4wNSI+PHBhdGggZD0iTTM2IDM0aDR2MmgtNHYtMnptMC00aDR2MmgtNHYtMnptMC00aDR2MmgtNHYtMnptMC00aDR2MmgtNHYtMnoiLz48L2c+PC9nPjwvc3ZnPg==')] opacity-50"></div>
        
        <div className="max-w-6xl mx-auto px-4 py-16 relative">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-white/20 backdrop-blur rounded-2xl">
              <BookOpen className="w-8 h-8 text-white" />
            </div>
            <div>
              <h1 className="text-3xl lg:text-4xl font-bold text-white">Investment Glossary</h1>
              <p className="text-white/80 mt-1">Essential terms and definitions for real estate investors</p>
            </div>
          </div>
          
          {/* Stats */}
          <div className="flex flex-wrap gap-4 mt-6 mb-8">
            <div className="bg-white/20 backdrop-blur rounded-xl px-4 py-2">
              <span className="text-white/70 text-sm">Total Terms</span>
              <p className="text-white font-bold text-xl">{glossaryTerms.length}</p>
            </div>
            <div className="bg-white/20 backdrop-blur rounded-xl px-4 py-2">
              <span className="text-white/70 text-sm">Categories</span>
              <p className="text-white font-bold text-xl">{categories.length - 1}</p>
            </div>
          </div>
          
          {/* Search */}
          <div className="max-w-xl">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-white/60 h-5 w-5" />
              <input
                type="text"
                placeholder="Search terms..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-12 pr-4 py-4 bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl focus:ring-2 focus:ring-white/50 focus:border-transparent text-white placeholder-white/60 text-lg"
              />
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 py-12">
        {/* Filter */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-8">
          <div className="flex flex-col md:flex-row md:items-center gap-4">
            <div className="flex items-center gap-2">
              <Filter className="w-5 h-5 text-gray-400" />
              <span className="text-gray-600 font-medium">Filter by category:</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {categories.map(category => (
                <button
                  key={category}
                  onClick={() => setSelectedCategory(category)}
                  className={`px-4 py-2 rounded-xl text-sm font-medium transition ${
                    selectedCategory === category
                      ? 'bg-purple-600 text-white'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  }`}
                >
                  {category === 'all' ? 'All Categories' : category}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Results count */}
        <p className="text-gray-500 mb-6">{filteredTerms.length} terms found</p>

        {/* Terms List */}
        <div className="space-y-4">
          {filteredTerms.map((term, index) => (
            <div key={index} className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 hover:shadow-lg transition group">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 bg-gradient-to-br from-purple-100 to-indigo-100 rounded-xl flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                  <Book className="h-6 w-6 text-purple-600" />
                </div>
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-3 mb-2">
                    <h3 className="text-xl font-bold text-gray-900">{term.term}</h3>
                    <span className={`px-3 py-1 text-xs font-medium rounded-full ${getCategoryColor(term.category)}`}>
                      {term.category}
                    </span>
                  </div>
                  <p className="text-gray-600 leading-relaxed">{term.definition}</p>
                </div>
              </div>
            </div>
          ))}

          {filteredTerms.length === 0 && (
            <div className="text-center py-16">
              <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Search className="w-10 h-10 text-gray-300" />
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">No terms found</h3>
              <p className="text-gray-500">Try adjusting your search or filter criteria</p>
            </div>
          )}
        </div>
      </div>

      <Footer />
    </div>
  );
}
